export const TaggelMenu='TaggleMenu';
export const TaggelSearch='TaggelSearch';

export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FIALDER='LOGIN_FIALDER';
export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOAD_PROFILE='LOAD_PROFILE';
export const LOGOUT='LOGOUT';

export const GET_DATA_REQUIST='GET_DATA_REQUIST';
export const GET_DATA_SUCCESS='GET_DATA_SUCCESS';
export const GET_DATA_FIALDER='GET_DATA_FIALDER';


export const SELECT_VIDEO_REQUIST='SELECT_VIDEO_REQUIST';
export const SELECT_VIDEO_SUCCESS='SELECT_VIDEO_SUCCESS';
export const SELECT_VIDEO_FIALDER='SELECT_VIDEO_FIALDER';


export const NUMBER_SUBSCREBE_REQUIST='NUMBER_SUBSCREBE_REQUIST';
export const NUMBER_SUBSCREBE_SUCCESS='NUMBER_SUBSCREBE_SUCCESS';
export const NUMBER_SUBSCREBE_FIALDER='NUMBER_SUBSCREBE_FIALDER';

export const SET_SUBSCRIBING_REQUIST='SET_SUBSCRIBING_REQUIST';
export const SET_SUBSCRIBING_SUCCESS='SET_SUBSCRIBING_SUCCESS';
export const SET_SUBSCRIBING_FIALDER='SET_SUBSCRIBING_FIALDER';


export const GET_COMMENTS_REQUIST='GET_COMMENTS_REQUIST';
export const GET_COMMENTS_SUCCESS='GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FIALDER='GET_COMMENTS_FIALDER';

export const WRITE_COMMENT_REQUIST='WRITE_COMMENT_REQUIST';
export const WRITE_COMMENT_FIALDER='WRITE_COMMENT_FIALDER';


export const RELITED_VIDEO_REQUIST='RELITED_VIDEO_REQUIST';
export const RELITED_VIDEO_SUCCESS='RELITED_VIDEO_SUCCESS';
export const RELITED_VIDEO_FIALDER='RELITED_VIDEO_FIALDER';

export const SEARCH_REQUIST='SEARCH_REQUIST';
export const SEARCH_SUCCESS='SEARCH_SUCCESS';
export const SEARCH_FIALDER='SEARCH_FIALDER';


export const SUBSCRIPTIONS_REQUIST='SUBSCRIPTIONS_REQUIST';
export const SUBSCRIPTIONS_SUCCESS='SUBSCRIPTIONS_SUCCESS';
export const SUBSCRIPTIONS_FIALDER='SUBSCRIPTIONS_FIALDER';